project_name: kitti
train_set: train
val_set: val
num_gpus: 1
num_workers: 0
batch_size: 4
image_size: 1280
obj_list: ["Car", "Van", "Truck", "Pedestrian", "Person_sitting", "Cyclist", "Tram"]

anchors_ratios: '[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]'
anchors_scales: '[2 ** 0, 2 ** (1.0/3.0), 2 ** (2.0/3.0)]'

mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
